exclude: .*migrations\/.*

ci:
  autoupdate_schedule: weekly
  skip: []

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: tests/.*\.py
          - id: check-yaml
          - id: check-case-conflict
          - id: detect-private-key
          - id: detect-aws-credentials

    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.7'
      hooks:
        - id: bandit
          args: [ "-c", "pyproject.toml" ]
          additional_dependencies: [ "bandit[toml]" ]

    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
        - id: isort

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.2.1
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
