#!/bin/bash

set fileformat=unix


python3 manage.py migrate
python3 manage.py makemigrations
python3 manage.py check_db
#python manage.py load_fixtures
#python manage.py collectstatic --noinput
gunicorn -c config/gunicorn/gunicorn_dev_config.py config.wsgi:application --reload
