#!/bin/bash

# Check if running inside Docker
if [ -f /.dockerenv ]; then
    export DB_HOST=db
else
    export DB_HOST=localhost
fi

python3 manage.py migrate
python3 manage.py makemigrations
python3 manage.py check_db
python3 manage.py collectstatic
python3 manage.py check_or_create_user
gunicorn -c config/gunicorn/gunicorn_dev_config.py
#python manage.py load_fixtures
