#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python backend/manage.py migrate --noinput
python backend/manage.py makemigrations --noinput
python backend/manage.py check_db
#python manage.py load_fixtures
#python manage.py collectstatic --noinput
gunicorn -c  backend/config/gunicorn/gunicorn_dev_config.py backend.config.wsgi:application
