name: Backend tests
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_USER: django
                    POSTGRES_PASSWORD: django
                    POSTGRES_DB: django_test
                ports:
                    - 5432:5432
            redis:
                image: redis:7
                ports:
                    - 6379:6379

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Cache Python dependencies
            uses: actions/cache@v4
            with:
              path: ~/.cache/pip
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/dev-requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r backend/requirements/requirements.txt
              pip install -r backend/requirements/dev-requirements.txt
          
          - name: Create .env from env.example
            run: |
              echo "Creating .env from env.example"
              cp .env/.env.example .env/.env.dev

          - name: Load environment variables
            run: |
              echo "Loading environment variables"
              set -o allexport
              source .env/.env.dev
              set +o allexport
          
          - name: Run migrations
            env:
              DATABASE_URL: postgres://django:django@localhost:5432/django_test
              DJANGO_SETTINGS_MODULE: config.settings.test_settings

            run: |
              python backend/manage.py migrate

          - name: Run celery worker
            env:
              REDIS_URL: redis://localhost:6379/0
            run: |
              celery -A backend.celery worker -l info

          - name: Run celery beat
            env:
              REDIS_URL: redis://localhost:6379/0
            run: |
              celery -A backend.celery beat -l info

          - name: Run tests
            env:
              DATABASE_URL: postgres://django:django@localhost:5432/django_test
              REDIS_URL: redis://localhost:6379/0
              DJANGO_SETTINGS_MODULE: config.settings.test_settings
            run: |
              python backend/manage.py test --settings=config.settings.test_settings
