name: Deploy to Production

on:
  push:
    branches: [ 'main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini deploy.yml
